all: BST1 BST2 AVL 
	
BST1: TestLeaves.cpp
	g++ TestLeaves.cpp -o TestLeaves

BST2: TestDeep.cpp
	g++ TestDeep.cpp -o TestDeep

AVL: TestBalance.cpp
	g++ TestBalance.cpp -o TestBalance

clean:
	rm -f TestLeaves TestDeep TestBalance
    
